version: '3.6'
services:
  local:
    container_name: fabric-local
    image: sacredwizard/fabric_local:latest
    build: .
    ports:
      - 8080:8080
      - 8081:8081
      - 4200:4200
    volumes:
      - /Users/rakeshr/test/block/fabric/aircraft:/home/wizard/fabric
    networks:
      - fabric-local
    tty: true

networks: 
  fabric-local: